const products = [
  {
    title: "Magnetite",
    category: 8,
    price: 89.0,
    img: "../../assets/img/1.jpg",
    band: "Scalene",
    year: 2017,
    id: 0,
  },
  {
    title: "Acabou o Chorare",
    category: 2,
    price: 66.0,
    img: "../../assets/img/2.jpg",
    band: "Novos Baianos",
    year: 1972,
    id: 1,
  },
  {
    title: "Nirvana Discografia",
    category: 8,
    price: 50.0,
    img: "../../assets/img/3.jpg",
    band: "Nirvava",
    year: 1990,
    id: 2,
  },
  {
    title: "Both Sides",
    category: 1,
    price: 22.0,
    img: "../../assets/img/4.jpg",
    band: "Phil Collins",
    year: 1993,
    id: 3,
  },
  {
    title: "The Queen is Dead",
    category: 8,
    price: 28.0,
    img: "https://m.media-amazon.com/images/I/51Bgnrde4OL._AC_.jpg",
    band: "The Smiths",
    year: 1986,
    id: 4,
  },
  {
    title: "Nada como um dia após o outro dia",
    category: 7,
    price: 45.0,
    img: "https://www.vagalume.com.br/racionais-mcs/discografia/nada-como-um-dia-apos-o-outro-dia.webp",
    band: "Racionais Mc's",
    year: 2002,
    id: 5,
  },
  {
    title: "Extraordinário Amor de Deus",
    category: 11,
    price: 32.0,
    img: "https://www.vagalume.com.br/aline-barros/discografia/extraordinario-amor-de-deus.webp",
    band: "Aline Barros",
    year: 2011,
    id: 6,
  },
  {
    title: "The Singles Box Set",
    category: 6,
    price: 62.0,
    img: "https://www.vagalume.com.br/eminem/discografia/the-singles-box-set.webp",
    band: "Eminem",
    year: 2003,
    id: 7,
  },
  {
    title: "The Singles Box Set",
    category: 1,
    price: 54.0,
    img: "https://www.vagalume.com.br/justin-timberlake/discografia/the-20-20-experience.webp",
    band: "Eminem",
    year: 2013,
    id: 8,
  },
];

const categories = [
  "Todos",
  "Pop",
  "MPB",
  "Forró",
  "Samba",
  "Baião",
  "Rap",
  "Hip-Hop",
  "Rock",
  "Reggae",
  "Country",
  "Gospel",
];
